name: Build & Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'dotnet-app/**'
      - '.github/workflows/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.gitignore'
  release:
    types: [ published ]

jobs:
  docker_publish:
    name: Build dockerfile and publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: admiralwoop/certbot
        tags: |
          type=raw,value=latest
          type=ref,event=branch,suffix=-{{sha}}
          type=semver,pattern={{version}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/arm/v7
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
